version: "3.9"
services:
  src:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.main:app --host 0.0.0.0 --reload --port 8000'
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    environment:
      - DATABASE_URL=postgresql://lottery_admin:lottery_password@db:5432/lottery_db
      - EXECUTION_HOUR=23:58
      - REFRESH_RATE=15
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=lottery_admin
      - POSTGRES_PASSWORD=lottery_password
      - POSTGRES_DB=lottery_db

volumes:
  postgres_data: